In [142]:
import cv2
import numpy as np
import math
from scipy.integrate import simps

In [143]:
def gaussFunction(x, sigma):
    return (1/(sigma*math.sqrt(2*math.pi))) * math.exp((-0.5)*(x**2/sigma**2))

def calculateGaussIntegral(lower_bound, upper_bound, sigma):
    integrateArray = np.linspace(lower_bound, upper_bound, num=1000)
    vGaussFunction = np.vectorize(gaussFunction) # Vectorized Gaussian Function
    y = vGaussFunction(integrateArray, sigma) # Y-values of gauss function for each interval
    integral = integrate.simps(y,integrateArray) # Integrating
    return integral

# Parameter: sigma (default 1)
# Return: 3x3 Gauss Kernal with given sigma value
def generateGaussKernal(sigma=1):
    kernel = np.ones((3,3))
    integrals = [calculateGaussIntegral(-1.5, -0.5, sigma), calculateGaussIntegral(-0.5, 0.5, sigma), calculateGaussIntegral(0.5, 1.5, sigma)] # Integral Values
    for i in range(0,3):
        for j in range(0,3):
            kernel[i][j]*=integrals[i]*integrals[j]
    normalizer = np.sum(kernel) # The Normalization Factor
    normalizedKernel = kernel/normalizer # Normalizing
    return normalizedKernel

In [144]:
generateGaussKernal(sigma=1)

array([[0.07784664, 0.12331683, 0.07784664],
       [0.12331683, 0.19534613, 0.12331683],
       [0.07784664, 0.12331683, 0.07784664]])

In [145]:
generateGaussKernal(sigma=2)


array([[0.10205828, 0.11534906, 0.10205828],
       [0.11534906, 0.13037066, 0.11534906],
       [0.10205828, 0.11534906, 0.10205828]])

In [114]:
calculateGaussIntegral(-0.5, 0.5, 1)

0.3829249225259412

In [105]:
# Testing Gauss Function
gaussFunction(0, 1)

0.3989422804014327

In [94]:
# Testing Integral
def f1(x):
    return x**2
x = np.linspace(1, 4, num=1000)
y1 = f1(x)
I1 = integrate.simps(y1,x)
print(I1)

21.000000004513527


In [92]:
np.linspace(-0.5, 0.5, num=1000)

array([-0.5       , -0.498999  , -0.497998  , -0.496997  , -0.495996  ,
       -0.49499499, -0.49399399, -0.49299299, -0.49199199, -0.49099099,
       -0.48998999, -0.48898899, -0.48798799, -0.48698699, -0.48598599,
       -0.48498498, -0.48398398, -0.48298298, -0.48198198, -0.48098098,
       -0.47997998, -0.47897898, -0.47797798, -0.47697698, -0.47597598,
       -0.47497497, -0.47397397, -0.47297297, -0.47197197, -0.47097097,
       -0.46996997, -0.46896897, -0.46796797, -0.46696697, -0.46596597,
       -0.46496496, -0.46396396, -0.46296296, -0.46196196, -0.46096096,
       -0.45995996, -0.45895896, -0.45795796, -0.45695696, -0.45595596,
       -0.45495495, -0.45395395, -0.45295295, -0.45195195, -0.45095095,
       -0.44994995, -0.44894895, -0.44794795, -0.44694695, -0.44594595,
       -0.44494494, -0.44394394, -0.44294294, -0.44194194, -0.44094094,
       -0.43993994, -0.43893894, -0.43793794, -0.43693694, -0.43593594,
       -0.43493493, -0.43393393, -0.43293293, -0.43193193, -0.43